### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2-bootstrap5#2]
@simialbi I've added a package to packagist. Is it ready to be tagged 1.0.0?

**Comment by simialbi** [comment]
@samdark I'll crosscheck today and will give the ok afterwards

**Comment by simialbi** [comment]
Should be ok to go with 1.0.0

**Comment by samdark** [comment]
@bizley would you please do extra read before tagging it?

**Comment by bizley** [comment]
1. https://github.com/yiisoft/yii2-bootstrap5/blob/master/.github/workflows/build.yml - we need to test on php 5.4+
2. Guides need to be updated but we can do it later on (or now?).
3. Code has PHP 7+ features so if we don't plan to support older versions it's fine, otherwise it needs downgrading.

**Comment by samdark** [comment]
Docs should be up to date for certain.

**Comment by simialbi** [comment]
1. Supporting php `>=7.0` is discussable, php `5.4`, `5.5`, `5.6` is imho outdated
2. I updated the class names, added new widgets, and removed a big part of the migration guide (difference between bs4 and bs5 is not as big as bs3 to bs4)
3. See 1

**Comment by bizley** [comment]
I'm all for using newest PHP versions but it's Yii 2 and people still using it on 5.x.

**Comment by bizley** [comment]
![Screenshot from 2021-08-03 10-32-11](https://user-images.githubusercontent.com/8577314/127984385-c881ad3c-50ee-4f90-9c0a-d4260842b6f9.png)

**Comment by simialbi** [comment]
ok, but I think nearby all of them are using bs3. Compared to yii2-bootstrap4 statistics there are just some `5.6`er:
![image](https://user-images.githubusercontent.com/3023342/127985990-4970752f-cd39-4e7a-b2a2-042ee90d0ffe.png)

**Comment by bizley** [comment]
If this is valid argument we would get rid of 5.x support in Yii 2, wouldn't we? ;)

**Comment by simialbi** [comment]
I would agree immediately 😊😉. But I know what you mean. We need a decision here. @samdark ?

**Comment by samdark** [comment]
![image](https://user-images.githubusercontent.com/47294/128006954-2d04815b-cb85-4a49-abbe-b58977956662.png)

3.6% total. That means there are alive Yii 2 projects on v5.

**Comment by simialbi** [comment]
Means make the repository 5.4+ compatible?

**Comment by samdark** [comment]
I've meant that regarding framework package itself. Having different constraints for this package is alright since majority of new projects are started with at least PHP 7.

**Comment by bizley** [comment]
Ok, so only guide needs some updates.

**Comment by simialbi** [comment]
ok, I downgraded the code so it works with php >=7.0 and updated the docs (the languages I understand)

**Comment by simialbi** [comment]
I think now we could release `1.0.0`? @samdark , @bizley ?

**Comment by bizley** [comment]
To be updated yet:
- https://github.com/yiisoft/yii2-bootstrap5/blob/master/docs/guide/assets-setup.md#using-bowernpm-client-directly (dependencies)
- https://github.com/yiisoft/yii2-bootstrap5/blob/master/docs/guide/basic-usage.md (link to docs)
- https://github.com/yiisoft/yii2-bootstrap5/blob/master/docs/guide/usage-widgets.md#navbar-widget- (doc link)
- https://github.com/yiisoft/yii2-bootstrap5/blob/master/docs/guide/helper-html.md (static controls link)

BTW looks we miss the chance to support 5.1.0 from the very beginning. Or maybe?

**Comment by simialbi** [comment]
Thanks for your feedback. I updated docs.
What do you mean with miss the chance to support 5.1, There are not so big changes? The biggest one imho is the Offcanvas in Navbar, and that's possible after last commit:
```php
NavBar::begin([
	'brandLabel' => 'Offcanvas navbar',
	'brandUrl' => ['/'],
	'options' => [
		'class' => ['navbar', 'navbar-light', 'bg-light', 'fixed-top']
	],
	'innerContainerOptions' => [
		'class' => ['container-fluid']
	],
	'collapseOptions' => false,
	'offcanvasOptions' => [
		'title' => 'Offcanvas',
		'placement' => Offcanvas::PLACEMENT_END
	]
]);
echo Nav::widget([
	'options' => [
		'class' => ['navbar-nav']
	],
	'items' => [
		['label' => 'Home', 'url' => '#'],
		['label' => 'Link', 'url' => '#'],
		['label' => 'Dropdown', 'items' => [
			['label' => 'Action', 'url' => '#'],
			['label' => 'Another action', 'url' => '#'],
			'-',
			['label' => 'Something else here', 'url' => '#'],
		]]
	]
]);
NavBar::end();
```

**Comment by bizley** [comment]
Great. So just updating version in the docs and we are good to go.

**Comment by simialbi** [comment]
ok, docs are ready

**Comment by bizley** [comment]
Green light @samdark

**Comment by samdark** [comment]
Done. Thanks for preparing it!

**Comment by antichris** [comment]
FYI, composer does not work this way
https://github.com/yiisoft/yii2-bootstrap5/blob/2.0.0/composer.json#L4
