### ISSUE TITLE
Change dropdown default  cssclass

### ISSUE THREAD

**Issue by kmergen** [yiisoft/yii2-bootstrap5#21]
### What steps will reproduce the problem?
Form Dropdown

### What is the expected result?
```
<select class="form-select"></select>
```

### What do you get instead?
```
<select class="form-control"></select>
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |  2.0.43
| PHP version     | 8.0
| Operating system  | Windows 10 on dev and Debian on prod

**Comment by simialbi** [comment]
Fixed by #23
