### ISSUE TITLE
Aria/data attributes

### ISSUE THREAD

**Issue by WinterSilence** [yiisoft/yii2-bootstrap5#27]
### What steps will reproduce the problem?

Yii2 and this package support short syntax for data/aria attributes (`'data' => ['suffix' => '...', 'suffix2' => '...']`), but don't have methods to merge attributes using long syntax (`['data-suffix' => '...']`) with short syntax (`['data' => ['suffix' => '...']]`).  This package uses both syntaxes, which only increases the chance of making error.

Two lines from single method:
https://github.com/yiisoft/yii2-bootstrap5/blob/97a3b653b74f6dbff799d8cbf2acc716536b6d82/src/Modal.php#L292
https://github.com/yiisoft/yii2-bootstrap5/blob/97a3b653b74f6dbff799d8cbf2acc716536b6d82/src/Modal.php#L302

### Fix

I see two solutions:
1. add method to merge attributes
2. select one syntax and replace another

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.*
| PHP version      | any
| Operating system | any

**Comment by simialbi** [comment]
@bizley, @samdark may be a task for [yii2 repository](https://github.com/yiisoft/yii2)?

**Comment by WinterSilence** [comment]
@simialbi already - https://github.com/yiisoft/yii2/pull/19100 , but need fix attributes in this package too. Replace long syntax (['data-suffix' => '...']) to short syntax (['data' => ['suffix' => '...']]).
