### ISSUE TITLE
I18n translation

### ISSUE THREAD

**Issue by WinterSilence** [yiisoft/yii2-bootstrap5#28]
### What steps will reproduce the problem?

Default labels not translated

### What is the expected result?

~~~php
$label = ArrayHelper::remove($toggleButton, 'label', Yii::t('yii/bootstrap5', 'Show'));
~~~

### What do you get instead?

https://github.com/yiisoft/yii2-bootstrap5/blob/97a3b653b74f6dbff799d8cbf2acc716536b6d82/src/Modal.php#L239

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.*
| PHP version      | any
| Operating system | any

**Comment by simialbi** [comment]
I'm not sure if this makes sense to implement. It will break the widgets if the translations are not configured in the application.
@bizley, @samdark What's your opinion?

**Comment by bizley** [comment]
It shouldn't break the app but it would require bootstrapping the new translation category. I would keep it as it is especially that user can provide own labels. Unless somewhere there is no option to do that - in that case we need to enable it.

**Comment by WinterSilence** [comment]
@simialbi we can configure translation in `BootstrapAsset::init()`, require only English version. users translates messages in application - it's better/handy than redefine labels for every widget instance.

**Comment by samdark** [comment]
@simialbi if translation isn't found it falls back to the message itself which is usally English (in case of Yii2). I think it is fine to implement it.

**Comment by simialbi** [comment]
@samdark There is no fallback:
https://github.com/yiisoft/yii2-bootstrap5/actions/runs/1657857625

**Comment by simialbi** [comment]
@samdark @bizley 
May be better to roll back?

**Comment by bizley** [comment]
What about adding the new category in bootstrapping process?

**Comment by simialbi** [comment]
Good idea. But how do you plan to achieve that without Module?

**Comment by bizley** [comment]
Like this: https://www.yiiframework.com/doc/api/2.0/yii-base-bootstrapinterface although I have never used it before.

**Comment by simialbi** [comment]
Yes that's possible, but where to call it? Still needs an addition in configuration...

**Comment by bizley** [comment]
> The first approach is mainly used by extensions and is managed by the Composer installation process. You mainly need to list the bootstrapping class of your extension in the composer.json file like following...
> If the extension is installed, the bootstrap information will be saved in yii\base\Application::$extensions.

**Comment by samdark** [comment]
@simialbi to roll back what exactly?

**Comment by simialbi** [comment]
@samdark This commit:
https://github.com/yiisoft/yii2-bootstrap5/commit/cb48dd6e4529b3d20f99e0020db5bdcd7239aea5

**Comment by simialbi** [comment]
@bizley seems to work: https://test.dev.tonic.ag/site/test-bootstrap
**extensions.php**
```php
  //[...]
  'yiisoft/yii2-bootstrap5' => 
  array (
    'name' => 'yiisoft/yii2-bootstrap5',
    'version' => 'dev-master',
    'alias' => 
    array (
      '@yii/bootstrap5' => $vendorDir . '/yiisoft/yii2-bootstrap5/src',
    ),
    'bootstrap' => 'yii\\bootstrap5\\i18n\\TranslationBootstrap',
  ),
  //[...]
```

translated rendered alert (*aria-label*):
```html
<div id="w12" class="alert-dark alert alert-dismissible" role="alert">

A simple dark alert—check it out!
<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Schliessen"></button>

</div>
```

**Comment by samdark** [comment]
@simialbi still need a rollback or no?

**Comment by simialbi** [comment]
@samdark No seems to work with bootstrapping via composer.jon
