### ISSUE TITLE
Refactore primitive widgets in helpers

### ISSUE THREAD

**Issue by WinterSilence** [yiisoft/yii2-bootstrap5#32]
I don't find any reason to realize primitive BS components like as `.btn`, `.progress` and etc. as widgets, there are enough single methods in `Html` helper. Widgets works much slower and uses more memory, because triggering 3 unwatched events for every instance.
Need convert classes as `Button`, `Progress`, `Alert`, `ButtonGroup` and `ButtonToolbar` to `Html` methods. 
To simply customization components we can implement class/attribute/options presets and pass preset name(s) to helper-methods in `$options` property:
~~~php
class Html extends BaseHtml
{
    /**
     * @var string[] the option/attribute presets grouped by methods
     */
    protected static $optionPresets = [
          'buttonClose' => [
                'default' => [],
                'white' => ['class' => 'btn-close-white'],
                'small' => ['class' => 'text-small'],
           ],
    ];

    public function presetOptions(string $methodName, string $presetName, array $options)
    {
             // normalize $options and merge into static::$optionPresets 
    }

    protected static function normalizeOptions(string $method, array $defaults, array $options): array
    {
         $presets = ArrayHelper::remove($options, 'preset', 'default');
         // preset names separated by whitespace
         $presets = explode(' ', $presets);
         $options = [$defaults, $options];
         foreach ($presets as &$preset) {
                $options[] = static::$optionPresets[$method][$preset] ?? [];
         }
        // optionally, converts ['data' => ['a' => 'b'], 'ariaLabel' => 'z'] to ['data-a' => 'b', 'aria-label' => 'Close dialog']
         // returns $options merged into flatten array
   }

    public static function buttonClose(array $options = []): string
    {
        $options = static::normalizeOptions(__FUNCTION__, ['class' => 'btn-close', 'aria-label' => null], $options);
        if ($options['aria-label'] === null) {
            $options['aria-label'] = Yii::t('yii/bootstrap5', 'Close');
        }
        $tag = ArrayHelper::remove($options, 'tag', 'button');
        if ($tag === 'a') {
              $options += ['role' => 'button', 'href' => '#'];
        }
        return static::{$tag}('', $options);
    }
}
~~~
~~~php
Html::buttonClose(['preset' => 'white small', 'tag' => 'a']);
~~~

**Comment by simialbi** [comment]
@samdark @bizley your opinion to this? It would make sense, but break "compatibility" to packages like [yii2-bootstrap](https://github.com/yiisoft/yii2-bootstrap) or [yii2-bootstrap4](https://github.com/yiisoft/yii2-bootstrap4)

**Comment by samdark** [comment]
@WinterSilence what's the performance difference per typical page? This change, if done, has at least the following drawbacks:

1. It breaks backwards compatibility.
2. It breaks ability to set defaults via widget factory.

**Comment by WinterSilence** [comment]
@samdark 
> what's the performance difference per typical page?

 CRUD index/list view: 25 records/rows on page **x** 2 buttons(edit and delete)  = minimum 50 widgets

> It breaks backwards compatibility.

"convert" does not necessarily mean "remove" - we can save widget classes, but add helper-methods in new minor version
**or**
> MAJOR version when you make incompatible API changes

Such global changes are reason to new major version

**Comment by samdark** [comment]
How much time does it take for 50 widgets?

> "convert" does not necessarily mean "remove" - we can save widget classes, but add helper-methods in new minor version

That sounds interesting but we should really measure the difference first. I doubt it's significant enough.

**Comment by WinterSilence** [comment]
@samdark widgets are not only slower, but also use more memory.

~~~php
Yii::beginProfile('Html::button');
$i = 100;
while (--$i > 0) {
    echo yii\bootstrap5\Html::button('Html::button'.$i, ['class' => 'btn-lg', 'id' => 'bh'.$i]);
}
Yii::endProfile('Html::button');

Yii::beginProfile('Button::widget');
$i = 100;
while (--$i > 0) {
    echo yii\bootstrap5\Button::widget(['label' => 'Button::widget'.$i, 'options' => ['class' => 'btn-lg', 'id' => 'bw'.$i]]);
}
Yii::endProfile('Button::widget');

var_dump(Yii::getLogger()->getProfiling());
~~~
**Html::button:**
duration 0.0053
memory 2499256
**Button::widget:**
duration  0.0128
memory 2594392

**Comment by bizley** [comment]
Although the performance impact is not significant (but still, there is one), the more important question for me is "are we forcing anyone to use widgets?" because the quick search didn't show me anything. If there are no widgets forced by default on the end users (like in grid columns etc.) there is nothing we must do, otherwise there is something to discuss. So in summary - if users can choose between using a widget and a simple helper it's great. And we don't have to prepare special versions of simple helpers just to mimic the widgets.

**Comment by WinterSilence** [comment]
@bizley > And we don't have to prepare special versions of simple helpers just to mimic the widgets.

what's you mean?

**Comment by samdark** [comment]
Nope, we're not forcing anyone to use widgets, they're just convenient.

**Comment by bizley** [comment]
@WinterSilence I'm saying that there is no big need to prepare special methods in the Html helper for generating Bootstrap buttons for example.

Ok, since we are not forcing anyone, the above statement stands I think.

**Comment by samdark** [comment]
1. Memory footprint is not significant, 95 kb.
2. Timings are more significant, it's 40ms for 100 widgets so for heavy pages displaying list of records with many controls it could be significant.

A good way to approach it is to introduce a helper and do a refactoring to use it in widgets. Important part here is to keep full backwards compatibility in widgets.

**Comment by WinterSilence** [comment]
@bizley

> no big need to prepare special methods in the Html helper for generating Bootstrap buttons for example.

hm... for example, it's code to generate BS5 button:

~~~php
class Html extends BaseHtml
{
  public static function button($content = '', $options = []): string
  {
      $content = (string) $content;
      $encode = ArrayHelper::remove($options, 'encode', false);
      if (!empty($encode) && !static::isHtml($content)) {
          $content = static::encode($content);
      }

      $options['class'] = (array) $options['class'] ?? [];

      array_unshift($options['class'], 'btn');

      $tag = ArrayHelper::remove($options, 'tag', 'button');
      if ($tag === 'a') {
          $options['role'] = 'button';
          if (!isset($options['href'])) {
              $options['href'] = '#';
          }
          if (!empty($options['disabled'])) {
              if (isset($options['aria'])) {
                  $options['aria']['disabled'] = 'true';
              } else {
                  $options['aria-disabled'] = 'true';
              }
              $options['tabindex'] = '-1';
              Html::addCssClass($options, 'disabled');
              unset($options['disabled']);
          }
      } else {
          unset($options['role'], $options['href'], $options['aria-disabled']);
      }

      return parent::button($content, $options);
  }
}
~~~
how you planed do it without any changes? copy code manually in views using buttons?

**Comment by samdark** [comment]
I mean something like this:

```php
use yii\bootstrap5\Html;

class Button extends Widget
{
    // ...
    public function run(): string
    {
        $options = [
            'encode' => $this->encodeLabel,
            'tag' => $this->tagName,
        ];

        return Html::button($this->label, $this->options);
    }
}
```

**Comment by WinterSilence** [comment]
@samdark

> I mean something like this:

it's not so easy as you think and it's still triggers 3 events for every widget


> Memory footprint is not significant, 95 kb.

Slow loading are compensated by caching, unlike memory leaks. For example, online service with 500 users online loose 100kb x 500!

**Comment by samdark** [comment]
> Slow loading are compensated by caching, unlike memory leaks. For example, online service with 500 users online loose 100kb x 500!

Nope. That's peak memory usage. The memory is **not** leaked in case of using widgets and should stay the same regardless on how many widgets are there. Try increasing number of widgets to 1000 in your tests and check if there is any significant difference in memory usage.

> it's not so easy as you think and it's still triggers 3 events for every widget

Yes. I mean, if you need no events then use `Html::button()` directly.

**Comment by bizley** [comment]
> hm... for example, it's code to generate BS5 button [...]

No, this code would be to generate BS5 button if you would like to prepare universal solution for all documented cases of rendering the button via BS5. Right now when developer is adding BS5 button only thing that is needed is `Html::button()` filled with options that are required at the moment.

What we could do is to add BS-specific methods this library Helpers to generate this BS-specific pieces of html like buttons that would be universal like in your example.

**Comment by samdark** [comment]
> No, this code would be to generate BS5 button if you would like to prepare universal solution for all documented cases of rendering the button via BS5. Right now when developer is adding BS5 button only thing that is needed is Html::button() filled with options that are required at the moment.

Or just a bunch of HTML. That's even faster in rendering.

**Comment by samdark** [comment]
Thinking more about it, I think that the case isn't common enough to provide Html helpers for all the possible markup. If you need maximum performance, HTML or current Html helpers (not bootstrap-specific) is the way to go. If you don't then current widgets are alright.

**Comment by samdark** [comment]
@WinterSilence thanks for raising the issue anyway and for providing numbers.

**Comment by WinterSilence** [comment]
@bizley 
> Right now when developer is adding BS5 button only thing that is needed is Html::button() filled with options that are required at the moment.

i.e. right now, these widgets are useless

@samdark 
> Try increasing number of widgets to 1000 in your tests and check if there is any significant difference in memory usage.

check it on my benchmark. that's right only in theory

@samdark @bizley 

`Html` methods must renders single tags, widgets must renders tag compositions, like as complex BS5 components

**Comment by samdark** [comment]
> check it on my benchmark. that's right only in theory

I've checked your numbers. If these are different with 1000 widgets then it might be an issue with garbage-collecting something and should be addressed.

**Comment by WinterSilence** [comment]
@samdark show your solution for this case
You constantly forget
- here is not "stackoverflow" and I'm don't ask you "why" or "how fix"
- that knowledge level of framework's users is usually lower than that of its developers

**Comment by samdark** [comment]
@WinterSilence my solution for this case is to use HTML.

**Comment by WinterSilence** [comment]
@samdark we talk about current package

**Comment by samdark** [comment]
1. You cannot speed up current widgets.
2. Simple ones are... well, simple. If you need maximum performance you can use HTML without much hassle.

Thus, introducing Html helper doesn't add much value in my opinion and nothing should be done.
