### ISSUE TITLE
User Authentication plugin compatibility

### ISSUE THREAD

**Issue by skills-up** [yiisoft/yii2-bootstrap5#35]
I'm unable to find any Yii2 User Authentication plugin compatible with yii2-bootstrap5. All the common plugins require either yii2-bootstrap or yii2-bootstrap4.

Kindly help.

**Comment by simialbi** [comment]
Hi @skills-up 

What exactly do you mean with "user authentication plugin"? Do you have an example of a "common plugin"?

**Comment by simialbi** [comment]
Yeah in this case that's in the responsibility of @2amigos
