### ISSUE TITLE
clientOptions false still renders JS

### ISSUE THREAD

**Issue by julianrutten** [yiisoft/yii2-bootstrap5#36]
### What steps will reproduce the problem?
Render a widget with `clientOptions` set to `false`. `registerPlugin` on `BootstrapWidgetTrait` is still run.  
### What is the expected result?
No JS plugin is rendered. Calling the javascript can then be done manually.
### What do you get instead?
It is rendered (and jQuery is not available on page load so it causes a console error).

### Additional info
In `yii2-bootstrap4` this was excluded:
https://github.com/yiisoft/yii2-bootstrap4/blob/master/src/BootstrapWidgetTrait.php#L76

However this conditional is not present in this library:
https://github.com/yiisoft/yii2-bootstrap5/blob/master/src/BootstrapWidgetTrait.php#L79

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.44
| PHP version      | 7.4
| Operating system | Ubuntu 20.04 LTS

**Comment by WinterSilence** [comment]
@julianrutten 🤦🏻‍♂️ you pass boolean value in array property

**Comment by julianrutten** [comment]
@WinterSilence I know that, I am not the one who made this spec I am merely trying to keep it compatible. Also whats up with the attitude? You must be fun to program with lol.

**Comment by WinterSilence** [comment]
@julianrutten 
> trying to keep it compatible 

compatible with what's? 
if you want extend behaviour, then update property comment too.

**Comment by julianrutten** [comment]
@WinterSilence The previous version of yii2 bootstrap library, you know the framework this is for that has NOT changed its major. It allowed you to skip the client side javascript to use your own. But I am kinda done with the emoticons, circle cant get square images and semver urls. I am trying to help out on an open source project here but I feel like I am overstaying my welcome here. Oh might want to list this breaking change in your migration guide:
https://github.com/yiisoft/yii2-bootstrap5/blob/master/docs/guide/migrating-yii2-bootstrap.md

Good luck with the library!

**Comment by WinterSilence** [comment]
@julianrutten 
> The previous version of yii2 bootstrap library, you know the framework this is for that has NOT changed its major. 

how does all this relate to framework? base widget don't have clientOptions property
`yii2-bootstrap5` not extend classes of `yii2-bootstrap4`.

> circle cant get square 

when something work not as you thinked, it's not bug. you want extend current behavior? no problem, but call a spade a spade.

> It allowed you to skip the client side javascript to use your own.

> if you want extend behaviour, then update property comment too.

**Comment by simialbi** [comment]
@WinterSilence you're right. I wouldn't say invalid, but bad style. An option would be nice anyway. I thought about do it the same way cause of habit of the programmers and it would be easier to upgrade

**Comment by julianrutten** [comment]
@WinterSilence Once again it was in `yii2-bootstrap` and `yii2-bootstrap4` I do not understand why you are making such a big deal here instead of just constructively trying to either reject this feature all together or come to a solution. Anyway I am not going to debate this with you because you are acting on bad faith here with the palm face emoticons and sending images and urls about stuff totally off topic.

**Comment by julianrutten** [comment]
@simialbi  I agree it is a bad style (not the modern way anymore) but it is the way it is done in yii2 in particular. However if you prefer strict typing this library I would gladly write the changes including tests and changelog.

**Comment by julianrutten** [comment]
@WinterSilence  Okay so after having a look at the library I have absolutely no clue why this is suddenly about strict typing because this library is nowhere near type safe.
https://github.com/yiisoft/yii2-bootstrap5/blob/master/src/Toast.php#L65
DateTime that can also be a boolean
Example 2:
https://github.com/yiisoft/yii2-bootstrap5/blob/master/src/Breadcrumbs.php#L48
An array that can be false (exactly the same as I proposed)

Should I go on?

**Comment by simialbi** [comment]
@julianrutten thx for your offer, I think we'll merge your initial pr

**Comment by WinterSilence** [comment]
@julianrutten 
> Breadcrumbs.php#L48

I didn't say it was impossible, I said it's not bug and you must update property comment to declare additional type.

**Comment by julianrutten** [comment]
No you didnt. @simialbi said that, after that you said: 🤦🏻‍♂️ its invalid. I asked 2 times constructively how to get past this but you went on with sending random stuff just to be condescending. Its kind of sad to be honest.
