### ISSUE TITLE
bootstrap@5.2.0-beta1

### ISSUE THREAD

**Issue by vbert** [yiisoft/yii2-bootstrap5#42]
How to update bootstrap to bootstrap@**5.2.0-beta1**?

**Comment by simialbi** [comment]
With the current version constraint it's not possible (because it only accept `stable` releases). A fork would be possible and changing the version constraint in the `composer.json`. You can then add your fork to `composer.json` like this:
```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/vbert/yii2-bootstrap5"
        }
    ]
}
```
