### ISSUE TITLE
Toast JS registration

### ISSUE THREAD

**Issue by SysMaven** [yiisoft/yii2-bootstrap5#44]
### What steps will reproduce the problem?
Using the Toast Widget as explained in the documentation
```
<?= yii\bootstrap5\Toast::widget([
            'title' => 'Toast',
            'dateTime' => 'now',
            'body' => 'Body',
]) ?>  
```

### What is the expected result?
The Toast component should be initialized/registered as per BS5 documentation.

### What do you get instead?
It appears that BootstrapWidgetTrait's registerPlugin() generates BS4 JS methods/code:
`jQuery('#w2').toast();`

Please see:
https://getbootstrap.com/docs/5.2/components/toasts/#usage

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |
| PHP version      |
| Operating system |

**Comment by simialbi** [comment]
`jQuery` is an integral part of `yii2`, so it should still work:
https://getbootstrap.com/docs/5.2/getting-started/javascript/#optionally-using-jquery
