### ISSUE TITLE
yii\bootstrap5\Breadcrumbs problem

### ISSUE THREAD

**Issue by t28hk** [yiisoft/yii2-bootstrap5#45]
if ($this->homeLink === []) {
            $links[] = $this->renderItem([
                'label' => 'Home',
                'url' => '/',
            ], $this->itemTemplate);
        } else {
            $links[] = $this->renderItem($this->homeLink, $this->itemTemplate);
        }

$homeLink set false,  has bug,  need a little change

        if(!($this->homeLink === false)){
            if ($this->homeLink === []) {
                $links[] = $this->renderItem([
                    'label' => 'Home',
                    'url' => '/',
                ], $this->itemTemplate);
            } else {
                $links[] = $this->renderItem($this->homeLink, $this->itemTemplate);
            }
        }

OR

        if ($this->homeLink === []) {
            $links[] = $this->renderItem([
                'label' => 'Home',
                'url' => '/',
            ], $this->itemTemplate);
        } elseif ($this->homeLink !== false) {
            $links[] = $this->renderItem($this->homeLink, $this->itemTemplate);
        }

**Comment by fetus-hina** [comment]
Are you using v2.0.2 or lower?

This issue looks already [reported by me](https://github.com/yiisoft/yii2-bootstrap5/pull/24) earlier and [has been fixed in v2.0.3](https://github.com/yiisoft/yii2-bootstrap5/blob/8cbb0f3a43c0067fda3838112d3d90805e17718b/CHANGELOG.md?plain=1#L14).

**Comment by t28hk** [comment]
> Are you using v2.0.2 or lower?
> 
> This issue looks already [reported by me](https://github.com/yiisoft/yii2-bootstrap5/pull/24) earlier and [has been fixed in v2.0.3](https://github.com/yiisoft/yii2-bootstrap5/blob/8cbb0f3a43c0067fda3838112d3d90805e17718b/CHANGELOG.md?plain=1#L14).

@fetus-hina Thanks for your reply, I use v2.0.2. It has been fixed, that is great.
