### ISSUE TITLE
Translation re-factoring

### ISSUE THREAD

**Issue by WinterSilence** [yiisoft/yii2-bootstrap5#55]
Need 
1. Extract code from `TranslationBootstrap::bootstrap()` into `BootstrapAsset::init()` - no need add it bootstrap and load every time
2. Move up `messages` directory - `src` must contain only class files

**Comment by simialbi** [comment]
1. If you put it in `BootstrapAsset::init` you lose the posibility to not use translations. With the bootstrap method you can choose.
2. I followed common usage (e.g. https://github.com/kartik-v/yii2-grid/tree/master/src)
