### ISSUE TITLE
Dropdown clientEvents do not fire

### ISSUE THREAD

**Issue by Sandritsch91** [yiisoft/yii2-bootstrap5#58]
According to the docs, the events should be bound either on the toggling element or on the .dropdown-menu parent element, not on the .dropdown-menu itself like it is now: [BS 5 Docs](https://getbootstrap.com/docs/5.2/components/dropdowns/#events)

> All dropdown events are fired at the toggling element and then bubbled up. So you can also add event listeners on the .dropdown-menu’s parent element.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.45
| PHP version      | >= 7.4
| Operating system | Windows Server 2019 Standard

**Comment by simialbi** [comment]
Is it just dropdown or every plugin?

**Comment by Sandritsch91** [comment]
I tested all other widgets and they work fine, so its only with the dropdown widget
