### ISSUE TITLE
Missing css files while including `yii\bootstrap5\BootstrapPluginAsset`

### ISSUE THREAD

**Issue by insthync** [yiisoft/yii2-bootstrap5#59]
### What steps will reproduce the problem?
Set `$depends` in `AppAsset` to 
```
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap5\BootstrapPluginAsset'
    ]
```

### What is the expected result?
Having bootstrap css files in `assets` folder

### What do you get instead?
No css files

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.45
| PHP version      |  8.1.12
| Operating system | Windows 10

**Comment by insthync** [comment]
I've temporarily avoided this issue by following instructions in https://github.com/yiisoft/yii2-bootstrap5/blob/master/docs/guide/assets-setup.md -> **Using CDN section**

By add 
```
        'assetManager' => [
            // override bundles to use CDN :
            'bundles' => [
                'yii\bootstrap5\BootstrapAsset' => [
                    'sourcePath' => null,
                    'baseUrl' => 'https://cdn.jsdelivr.net/npm/bootstrap@5.1/dist/',
                    'css' => [
                        'css/bootstrap.min.css'
                    ],
                ],
                'yii\bootstrap5\BootstrapPluginAsset' => [
                    'sourcePath' => null,
                    'baseUrl' => 'https://cdn.jsdelivr.net/npm/bootstrap@5.1/dist/',
                    'css' => [
                        'css/bootstrap.min.css'
                    ],
                    'js' => [
                        'js/bootstrap.bundle.min.js'
                    ],
                ],
            ],
        ],
```

to `config/web.php` (in `components`)

**Comment by xhostch** [comment]
Seems to be related to [#9741](https://github.com/yiisoft/yii2/issues/9741), ran into the same issue just the other way around (js files not present).

**Comment by julianrutten** [comment]
This is caused by #52.

**Comment by simialbi** [comment]
I think it's caused by the `only` clauses. Rolled back this change
