### ISSUE TITLE
Dropdown template is incorrect

### ISSUE THREAD

**Issue by shuhratjondev** [yiisoft/yii2-bootstrap5#73]
#### Official docs
https://getbootstrap.com/docs/5.2/components/dropdowns/#single-button
```
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    Dropdown button
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><a class="dropdown-item" href="#">Action</a></li>
    <li><a class="dropdown-item" href="#">Another action</a></li>
    <li><a class="dropdown-item" href="#">Something else here</a></li>
  </ul>
</div>
```

Your template is using div instead of ul
https://github.com/yiisoft/yii2-bootstrap5/blob/master/src/Dropdown.php#L166

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2
| PHP version      | *
| Operating system | *

**Comment by simialbi** [comment]
`div` is allowed to. At the latest if you have a form you need div: https://getbootstrap.com/docs/5.2/components/dropdowns/#forms

**Comment by shuhratjondev** [comment]
If I use it in navbar, it shows an error template https://getbootstrap.com/docs/5.2/components/navbar/#supported-content
