### ISSUE TITLE
Use both bs3 and bs5 in the same project

### ISSUE THREAD

**Issue by antoniom** [yiisoft/yii2-bootstrap5#77]
This is a similar to https://github.com/yiisoft/yii2-bootstrap4/issues/11

I have a PHP application which is mainly written with bs3 using yii2-bootstrap.
Now, there is a new part on it that needs to be done in bs5 while keeping bs3 for the existing parts.

Trying to install yii2-bootstrap5 (while having already installed yii2-bootstrap) gives me an error:
```sh
  Problem 1
    - Root composer.json requires yiisoft/yii2-bootstrap5 * -> satisfiable by yiisoft/yii2-bootstrap5[2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - yiisoft/yii2-bootstrap5[2.0.1, ..., 2.0.4] require bower-asset/bootstrap ^5.1.0 -> found bower-asset/bootstrap[v5.1.0, ..., v5.2.3] but the package is fixed to v3.4.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

yii2-bootstrap4 maintainers solved this by depending on "npm-asset/bootstrap" instead of "bower-asset", can you do the same for that repo ?

**Comment by simialbi** [comment]
Hi @antoniom 

Yeah possible, but what if you want to install bootstrap4 and bootstrap5?

**Comment by antoniom** [comment]
Correct observation; it will break compatibility for those users.

However npm permits 2 version of the same package to be installed. For example:
```sh
npm i bootstrap@5
npm i bs4@npm:bootstrap@4
```
[Source](https://stackoverflow.com/a/56495895/1149919)
The latter creates an alias named as bs4 which can be found under `node_modules/` directory.

Not sure if asset-packagist and fxp plugin can work that way with npm-asset

**Comment by simialbi** [comment]
The only reliable solution I know is to create a public package to `bs3` (`"bower-asset/bootstrap":"^3.0.0"`) with a `composer.json` with `provide` set. Try the following: use in your root `composer.json` in the require section `raiffeisen/bootstrap` like this:
```json
{
    "require": {
        "raiffeisen/bootstrap": "^3.4.0"
    }
}
```

It should prevent the install of `bower-asset/bootstrap 3.x` and allow the installation of `bower-asset/bootstrap 5.x`

If you do that, you have to override the configuration of the asset bundle in the yii app configuration:
```php
[
    'components' => [
        'assetManager' => [
            'bundles' => [
                'yii\bootstrap\BootstrapAsset' => [
                    'sourcePath' => '@vendor/raiffeisen/bootstrap/dist'
                ]
            ]
        ]
    ]
]
```

**Comment by antoniom** [comment]
I confirm it works! 

Didn't know the existence of the `provide` directive in composer.

Thanks @simialbi

**Comment by fastp-dev** [comment]
> The only reliable solution I know is to create a public package for `bs3` (`"bower-asset/bootstrap":"^3.0.0"`) with a `composer.json` with `provide` set. Try the following: use in your root `composer.json` in the require section `raiffeisen/bootstrap` like this:
> 
> ```json
> {
>     "require": {
>         "raiffeisen/bootstrap": "^3.4.0"
>     }
> }
> ```
> 
> It should prevent the install of `bower-asset/bootstrap 3.x` and allow the installation of `bower-asset/bootstrap 5.x`
> 
> If you do that, you have to override the configuration of the asset bundle in the yii app configuration:
> 
> ```
> [
>     'components' => [
>         'assetManager' => [
>             'bundles' => [
>                 'yii\bootstrap\BootstrapAsset' => [
>                     'sourcePath' => '@vendor/raiffeisen/bootstrap/dist'
>                 ]
>             ]
>         ]
>     ]
> ]
> ```
It works. Thank you so much!
