### ISSUE TITLE
Replace  `bower-asset/bootstrap` => `npm-asset/bootstrap`.

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/yii2-bootstrap5#81]
![image](https://github.com/yiisoft/yii2-bootstrap5/assets/42547589/192911a7-0209-426c-9d2a-3e00ad3e1996)

![image](https://github.com/yiisoft/yii2-bootstrap5/assets/42547589/f2266eb4-b64f-46f3-9d8f-7a60408f9fd4)

The bower package is not receiving any more updates.

**Comment by simialbi** [comment]
Seems to be fixed:
![image](https://github.com/yiisoft/yii2-bootstrap5/assets/3023342/74e2bad7-02b2-4f27-94ad-cec507f6e202)
