### ISSUE TITLE
Missing package twbs/boostrap-icons in composer.json

### ISSUE THREAD

**Issue by paalg** [yiisoft/yii2-bootstrap5#82]
### What steps will reproduce the problem?
```
composer create-project yiisoft/yii2-app-basic [foldername]
cd [foldername]
composer upgrade 
```
You now have Yii2 Basic installed with package yiisoft/bootstrap5 required as version ~2.0.2 in composer.json file (version 2.0.4). If you use any code that will access the yii2-bootstrap5\BootstrapIconAsset.php file, you will get an exception.

For example, if you install the package 2amigos/yii2-usuario, that uses the BootstraIconAsset.php file, you get the exception when you try to access the user/admin page.

To remove the error, you can require the package twbs/bootstrap-icons manually:
```
composer require twbs/bootstrap-icons
```

### What is the expected result?
No error

### What do you get instead?
Invalid Argument – [yii\base\InvalidArgumentException](https://www.yiiframework.com/doc-2.0/yii-base-invalidargumentexception.html)
The file or directory to be published does not exist: /var/www/lonnsslipp/vendor/twbs/bootstrap-icons/font

Exception thrown from file /vendor/yiisoft/yii2/web/AssetManager.php line 26:
```
\yii\bootstrap5\BootstrapIconAsset::register($this);
```
The error occurrs because the file yii2-bootstrap5/BootstrapIconAsset.php has its $sourcePath property set to "@vendor/twbs/bootstrap-icons/font", while the composer.json does not require it.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.49.3
| PHP version      | 8.2.15
| Operating system | Linux Mint 20.3

**Comment by razvanphp** [comment]
You mean this?

https://github.com/yiisoft/yii2-bootstrap5/blob/1a4f4d66c9ef3a076dc327999f8dc8b52caa5ac0/composer.json#L35

**Comment by simialbi** [comment]
It's in the `suggest` section too:
https://github.com/yiisoft/yii2-bootstrap5/blob/1a4f4d66c9ef3a076dc327999f8dc8b52caa5ac0/composer.json#L37-L39
We did not put it in the `require` section because there are a lot of people which does not use them, then it would be unnecessary overhead.
