### ISSUE TITLE
How to show offcanvas in full screen mode / is it supported?

### ISSUE THREAD

**Issue by siripravi** [yiisoft/yii2-bootstrap5#89]
### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |
| PHP version      |
| Operating system |

**Comment by siripravi** [comment]
I want to add the class "w-100" to offcanvas container to display it in full screen. How to do it?

**Comment by simialbi** [comment]
Configure like this:
```php
Offcanvas::widget(['options' => ['class' => ['w-100']]]);
```
